from pathlib import Path
import re
p = Path(__file__).resolve().parents[1] / 'app.js'
s = p.read_text(encoding='utf-8')
s = s.replace("const saveKey = 'on-the-brink.save.v1';", "const saveKey = 'on-the-brink.save.v2';")
s = s.replace("let state = null, view = 'home', storageOK = true, toastTimer;", "let state = null, view = 'home', storageOK = true, toastTimer, showHistoricalHints = false;")
s = s.replace("if (raw) { state", "if (!raw && localStorage.getItem('on-the-brink.save.v1')) notice('Обновлён сценарий: начните новую кампанию. Сохранение первой версии оставлено в браузере.');\n    if (raw) { state")
s = s.replace('15 ЭПИЗОДОВ', '${D.episodes.length} ЭПИЗОДОВ').replace('≈ 25–40 минут · 15 эпизодов', '≈ 45–70 минут · ${D.episodes.length} эпизодов')
s = s.replace('Факты отделены от условных последствий ваших решений.', 'Развилки истории, внутренняя политика и последствия вашего курса.')
s = s.replace('Пройдите через ключевые события холодной войны. Принимайте решения от лица руководителей США или СССР — и узнайте, какой ценой сохраняется равновесие.', 'Почему союзники стали противниками? Разберитесь в интересах сторон, выберите собственный курс и измените ход следующих событий. От восстановления Европы до будущего СССР — решения оставляют след.')

def function(name, content):
    global s
    pattern = r'^  function ' + re.escape(name) + r'\([\s\S]*?(?=^  function |^  document\.)'
    s, count = re.subn(pattern, lambda m: content.rstrip()+'\n', s, count=1, flags=re.M)
    if count != 1: raise ValueError(name)

function('metrics', '''  function metrics(values = state.stats, labels = D.metrics) {
    const hints = { tension: '100 — военная развилка', resources: 'Текущие средства на политику', influence: 'Политический вес вашей стороны', trust: 'Возможность заключать договоры', economy: 'Определяет будущие поступления', allies: 'Поддержка, а не число государств', readiness: 'Обычные силы и снабжение', stability: 'Способность проводить курс внутри страны' };
    return Object.entries(labels).map(([key,label]) => `<div class="metric ${key}"><div class="metric-head"><span>${label}</span><strong>${values[key]}</strong></div><div class="meter" role="meter" aria-label="${label}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${values[key]}"><span style="width:${values[key]}%"></span></div><p>${hints[key]}</p></div>`).join('');
  }
  function strategicPanel() {
    return `<div class="strategic-panel"><h3>Основа вашего курса</h3>${metrics(state.strategic,D.strategic)}<details class="rival-details"><summary>Состояние соперника</summary><p>Экономика: ${state.rival.economy}<br>Союзная поддержка: ${state.rival.allies}<br>Готовность армии: ${state.rival.readiness}</p><p>Условная реакция на ваш курс и фон эпохи. Это не реальные исторические измерения.</p></details></div>`;
  }''')
function('deltas', '''  function deltas(delta, labels = D.metrics, omitZero = false) {
    return `<div class="deltas">${Object.entries(labels).filter(([k]) => !omitZero || delta[k]).map(([k,label]) => { const n = delta[k] || 0, good = k === 'tension' ? n < 0 : n > 0; return `<span class="delta ${n === 0 ? 'neutral' : good ? 'good' : 'bad'}">${label} ${sign(n)}</span>`; }).join('')}</div>`;
  }
  function exposition(ep) {
    const x = ep.exposition;
    return `<section class="exposition"><span class="eyebrow">РАЗОБРАТЬСЯ В СИТУАЦИИ</span><h3>Как мы здесь оказались</h3><p>${esc(x.origin)}</p><h4>Чего хотят участники</h4><ul>${x.interests.map(t => `<li>${esc(t)}</li>`).join('')}</ul><div class="stakes"><h4>Почему ваше решение важно</h4><p>${esc(x.stakes)}</p></div></section>`;
  }
  function branchContext(ep) {
    const carry = state.phase === 'decision' ? E.carry(state) : state.history.at(-1)?.carry || [];
    return `${ep.branch ? `<section class="branch-card"><span class="eyebrow">ВАША АЛЬТЕРНАТИВНАЯ ИСТОРИЯ</span><h3>Прошлое изменило эту главу</h3><p>${esc(ep.branch.reason)}</p><details><summary>На чём основано допущение</summary><p>${esc(ep.branch.caveat)}</p>${sourceLinks(ep.branch.sources)}</details></section>` : ''}${carry.length ? `<details class="carry" open><summary>Что пришло из ваших прошлых решений</summary><ul>${carry.map(t => `<li>${esc(t)}</li>`).join('')}</ul></details>` : ''}`;
  }
  function fiscalPreview(c) {
    if(state.index === D.episodes.length-1 || E.availability(state,c)) return '';
    const next = D.episodes[state.index+1], p = E.preview(state,c);
    const idx = E.current(state).choices[state.side].indexOf(c);
    const after = E.choose(state,idx), budget = E.budget(after,next), before = E.budget(state,next);
    if(budget.net === before.net) return '';
    return `<span class="fiscal-preview">Регулярный бюджет в следующей главе: ${sign(budget.net)} (${sign(budget.net-before.net)} к прежнему курсу). Уже учитывает поступления и содержание.</span>`;
  }''')
function('decisions', '''  function decisions(ep) {
    return `${exposition(ep)}<div class="briefing"><span class="eyebrow">ВАША ПЕРСПЕКТИВА / ${esc(ep.leaders[state.side])}</span><p>${esc(ep.briefs[state.side])}</p></div><div class="choices-heading"><h3>Ваше решение</h3><button class="text-button" data-action="historical-hints">${showHistoricalHints ? 'Скрыть исторические подсказки' : 'Показать исторические подсказки'}</button></div><p class="route-state">${state.historical ? 'Вы пока следуете историческому маршруту.' : 'Ваш маршрут уже отличается от реального. Следующие главы учитывают принятый курс.'}</p><div class="choice-list">${ep.choices[state.side].map((c,i) => {
      const blocked = E.availability(state,c), p = E.preview(state,c);
      return `<button class="choice" data-action="choose" data-choice="${i}" ${blocked ? 'disabled' : ''}><span class="choice-number" aria-hidden="true">0${i+1}</span><span class="choice-main"><span class="choice-title">${esc(c.title)}</span>${showHistoricalHints && c.historical ? '<span class="history-hint">Историческое направление политики</span>' : ''}<span class="choice-detail">${esc(c.detail)}</span><span class="choice-why"><b>Зачем этот выбор:</b> ${esc(c.why || c.detail)}</span>${deltas(p.delta)}${deltas(p.strategicDelta,D.strategic,true)}${fiscalPreview(c)}${p.notes.length ? `<span class="choice-detail">${p.notes.map(esc).join(' ')}</span>` : ''}${blocked ? `<span class="lock-reason">${esc(blocked)}</span>` : ''}</span><span class="choice-arrow" aria-hidden="true">↗</span></button>`;
    }).join('')}</div><p class="model-note">Можно выбрать клавишами 1, 2, 3. Показатели — условная модель. Напряжённость 100 или прямое столкновение открывают военную развилку; нулевой бюджет останавливает курс.</p>`;
  }''')
function('result', '''  function result(ep) {
    const h = state.history.at(-1), c = h.selected;
    const next = state.ending || state.pendingWar || state.index === D.episodes.length-1 ? null : E.advance(state);
    const nextScene = next?.phase === 'decision' ? E.current(next) : null;
    return `<section class="consequence" id="result-panel" tabindex="-1"><span class="eyebrow">ПОСЛЕДСТВИЯ В ВАШЕЙ ВЕТКЕ</span><h3>${esc(c.title)}</h3><p>${esc(c.outcome)}</p>${deltas(h.delta)}${deltas(h.strategicDelta,D.strategic,true)}${h.notes.map(n => `<p>${esc(n)}</p>`).join('')}<span class="historical-badge ${c.historical ? '' : 'alternative'}">${c.historical ? 'Близко к реальному направлению политики' : 'Альтернативный ход · условный сценарий'}</span>${state.pendingWar ? '<p class="warning-line">Началось прямое столкновение. Следующий шаг — решение о пределах войны.</p>' : state.ending ? '<p class="warning-line">Доступный бюджет исчерпан. Дальше — итог курса.</p>' : ''}</section>${nextScene ? `<section class="next-preview"><span class="eyebrow">СЛЕДУЮЩИЙ ШАГ / ${nextScene.year}</span><h3>${esc(nextScene.title)}</h3><p>${esc(nextScene.branch?.reason || next.transition)}</p>${E.carry(next).slice(0,1).map(t=>`<p>${esc(t)}</p>`).join('')}</section>` : ''}${historyBox(D.episodes[state.index])}<div class="next-row"><span class="micro">Реальные события показаны отдельно. В вашей ветке сохраняются договоры, реформы, обязательства и изменения будущих сцен.</span><button class="primary" data-action="next">${state.pendingWar ? 'Решить судьбу столкновения' : state.ending || state.index === D.episodes.length-1 ? 'Посмотреть итоги' : 'Следующая глава'} <span>→</span></button></div>`;
  }''')
function('campaign', '''  function campaign() {
    view = 'game';
    if(state.phase === 'ending') { ending(); return; }
    if(['war','war_result'].includes(state.phase)) { warScreen(); return; }
    const ep = E.current(state);
    const risk = state.stats.tension >= 80 ? 'КРИТИЧЕСКАЯ НАПРЯЖЁННОСТЬ' : state.stats.tension >= 55 ? 'ОПАСНОЕ ПРОТИВОСТОЯНИЕ' : state.stats.tension >= 30 ? 'НЕУСТОЙЧИВОЕ РАВНОВЕСИЕ' : 'ЕСТЬ ПРОСТРАНСТВО ДЛЯ ДИАЛОГА';
    app.innerHTML = `<section class="campaign"><div class="campaign-top"><div><div class="eyebrow">КАМПАНИЯ / ${D.sides[state.side]}</div><h1>Хроника вашего курса</h1></div><div class="tools"><button class="secondary" data-action="journal">Журнал решений</button><span class="save-state">${storageOK ? '● Автосохранение' : '○ Без сохранения'}</span></div></div>${timeline()}<div class="game-layout"><aside class="sidebar" aria-label="Показатели кампании"><div class="side-label">${flag(state.side)}<span><b>${D.sides[state.side]}</b><small>${esc(ep.leaders[state.side])}</small></span></div>${metrics()}<div class="sidebar-note"><strong>${risk}</strong><br>Все шкалы условные: 0–100.</div>${strategicPanel()}</aside><div class="episode"><div class="stage"><img src="assets/world.svg" alt="" aria-hidden="true">${sceneArt(ep.motif)}<div class="stage-meta"><span>ГЛАВА ${String(state.index+1).padStart(2,'0')} / ${D.episodes.length}</span><span>${esc(ep.category).toUpperCase()}</span></div><div class="stage-title"><div class="year">${ep.year}</div><h2>${esc(ep.title)}</h2><p>${esc(ep.place)} · ${esc(ep.date)}</p></div></div><p class="transition">${esc(state.transition)}</p>${branchContext(ep)}<div class="narrative">${esc(ep.context)}</div>${state.phase === 'decision' ? decisions(ep) : result(ep)}</div></div></section>`;
    const current = app.querySelector('.time-node.current');
    if(current) current.parentElement.scrollLeft = Math.max(0,current.offsetLeft-current.parentElement.offsetLeft-current.parentElement.clientWidth/2);
  }
  function warScreen() {
    const h = state.history.at(-1), w = h.war, own = w?.before.strategic || state.strategic, rival = w?.rivalBefore || state.rival;
    app.innerHTML = `<section class="campaign war-screen"><div class="eyebrow">${D.episodes[state.index].year} / ВОЕННАЯ РАЗВИЛКА / ${D.sides[state.side]}</div><h1>Сдерживание сорвалось</h1><p class="war-intro">Ваш курс привёл к прямому столкновению. У обеих сторон остаётся ядерное оружие. Можно попытаться договориться, удержать большую войну в рамках обычных вооружений или перейти к ядерному применению.</p><section class="history-box"><h3>С чем стороны вошли в кризис</h3><table class="comparison"><thead><tr><th>Основа военных возможностей</th><th>${D.sides[state.side]}</th><th>${D.sides[state.side === 'usa' ? 'ussr' : 'usa']}</th></tr></thead><tbody>${['economy','allies','readiness'].map(k=>`<tr><th>${D.strategic[k]}</th><td>${own[k]}</td><td>${rival[k]}</td></tr>`).join('')}<tr><th>Условная сила</th><td>${w?.own ?? E.power(own)}</td><td>${w?.enemy ?? E.power(rival)}</td></tr></tbody></table><p class="micro">Формула: готовность × 40% + экономика × 30% + союзная поддержка × 30%, округление до целого. Преимущество от 8 пунктов даёт победу в обычной войне; меньше — истощение и перемирие. Эта формула — игровое допущение.</p></section>${state.phase === 'war' ? `<div class="choice-list">${E.warOptions(state).map((o,i)=>`<button class="choice" data-action="war-choice" data-choice="${i}" ${o.blocked?'disabled':''}><span class="choice-number">0${i+1}</span><span class="choice-main"><span class="choice-title">${o.title}</span><span class="choice-detail">${o.detail}</span>${o.blocked?`<span class="lock-reason">${o.blocked}</span>`:''}</span></button>`).join('')}</div>` : `<section class="consequence" id="result-panel" tabindex="-1"><h3>${esc(w.title)}</h3><p>${esc(w.text)}</p>${deltas(w.delta)}${deltas(w.strategicDelta,D.strategic,true)}</section><button class="primary" data-action="next">${state.ending?'Посмотреть итоги':'Продолжить после перемирия'} →</button>`}<section class="history-box war-evidence"><h3>Граница исторического знания</h3><p>Реальной полномасштабной войны СССР и США не было. Её победитель не установлен историками. Архивы Карибского кризиса показывают, что участники не знали обо всех средствах противника. Сохранение неядерного предела здесь — явное условие альтернативного сценария.</p>${sourceLinks(['nuclearRisk','cubaArchive'])}</section></section>`;
  }''')
s=s.replace('state.history.map(h => h.after.tension)', 'state.history.map(h => h.war?.after.stats.tension ?? h.after.tension)')
function('journalRows', '''  function journalRows() {
    return state.history.length ? state.history.map(h => `<div class="journal-row"><span>${h.scene.year}</span><div><strong>${esc(h.scene.title)}</strong><p>${esc(h.selected.title)}</p>${h.scene.branch ? `<p class="journal-branch">Ветка: ${esc(h.scene.branch.reason)}</p>` : ''}${deltas(h.delta)}${deltas(h.strategicDelta,D.strategic,true)}${h.war ? `<p><b>Военная развилка:</b> ${esc(h.war.title)}</p>${deltas(h.war.delta)}${deltas(h.war.strategicDelta,D.strategic,true)}` : ''}</div><small>${h.selected.historical ? 'ИСТОРИЧЕСКИЙ КУРС' : 'АЛЬТЕРНАТИВА'}</small></div>`).join('') : '<p>Ваши решения появятся после первого выбора.</p>';
  }''')
function('ending', '''  function ending() {
    view='game';
    const e=E.endings[state.ending],matched=state.history.filter(h=>h.selected.historical).length;
    const retry=state.ending==='exhaustion'||state.ending==='nuclear'||state.ending.startsWith('war_');
    app.innerHTML=`<section class="ending"><div class="ending-grid"><div><div class="eyebrow">${state.historical?'ИСТОРИЧЕСКАЯ КОНЦОВКА':'АЛЬТЕРНАТИВНАЯ КОНЦОВКА'} / ${D.sides[state.side]} / ${D.episodes[state.index].year}</div><h1>${e.title}</h1><p>${e.text}</p><p>Пройдено глав: <b>${state.history.length} из ${D.episodes.length}</b>. Исторических направлений политики: <b>${matched}</b>. Изменённых сцен: <b>${state.history.filter(h=>h.scene.branch).length}</b>.</p><div class="ending-actions"><button class="primary" data-action="export">Скачать журнал ↓</button><button class="secondary" data-action="home">В главное меню</button>${retry?'<button class="secondary" data-action="retry">Пересмотреть последнее решение</button>':''}</div><section class="ending-causes"><h3>Почему получился этот финал</h3><p>Подготовка реформ: ${state.flags.reforms}. Союзный договор: ${state.flags.unionAgreement?'согласован':'не закреплён'}. Добровольные партнёрства: ${state.flags.voluntaryBloc?'сформированы':'не сформированы'}. Экономика: ${state.strategic.economy}, поддержка союзников: ${state.strategic.allies}, устойчивость: ${state.strategic.stability}.</p><p>${state.historical?'Все главы пройдены по историческим направлениям; для каждой стороны предусмотрен собственный реальный итог.':'Исторические справки остаются в архиве. Данный итог — результат правил и допущений вашей ветки.'}</p></section></div><div>${chart()}<div class="ending-stats">${metrics()}</div><div class="ending-stats">${metrics(state.strategic,D.strategic)}</div></div></div><section class="journal"><div class="section-heading"><h2>След ваших решений</h2><span>ЛИЧНОЕ ДОСЬЕ</span></div>${journalRows()}</section></section>`;
  }''')
function('archive', '''  function archive() {
    openModal(`<h2 id="modal-title">Архив и объяснения</h2><p>Здесь — реальная история. Изменённые обстоятельства вашей кампании отмечаются непосредственно в главах.</p><h3>Словарь для первого знакомства</h3>${D.glossary.map(([term,text])=>`<details><summary>${esc(term)}</summary><p>${esc(text)}</p></details>`).join('')}<h3>Исторические главы</h3>${D.episodes.map(ep=>`<details><summary><span>${ep.year}</span>${esc(ep.title)}</summary><p>${esc(ep.exposition.origin)}</p><p>${esc(ep.history)}</p>${sourceLinks(ep.sources)}</details>`).join('')}<h3>Исследования и альтернативы</h3>${D.research.map(r=>`<details><summary>${esc(r.title)}</summary><h4>Что говорят источники</h4><p>${esc(r.evidence)}</p><h4>Что допущено в игре</h4><p>${esc(r.inference)}</p>${sourceLinks(r.sources)}</details>`).join('')}<p class="micro">Справки — авторский пересказ документов и исследований. Эксперты не рецензировали игру и не подтверждали её формулы. Лидеры и календарь сохранены как условные опорные точки; экономические и политические обстоятельства могут меняться.</p>`);
  }''')
function('guide', '''  function guide() {
    openModal(`<h2 id="modal-title">Как меняется история</h2><p>Кампания включает ${D.episodes.length} глав. Перед выбором объясняются причины конфликта, интересы участников и ставки решения. Архив помогает с терминами и реальными событиями.</p><ol class="guide-list"><li><b>Прошлое меняет следующие сцены.</b> Общая программа восстановления может предотвратить блокаду Берлина; открытый город и доверие — создать превентивные гарантии по Кубе. Реформы, расходы и договоры сохраняются до финала.</li><li><b>Бюджет и экономика различаются.</b> Бюджет тратится сейчас. Поступления за главу: 5 + целая часть экономики / 15; научная программа добавляет 2. Из них вычитаются содержание армии, внешние обязательства и отложенные расходы. Точный расчёт виден под иллюстрацией.</li><li><b>Союзники и готовность.</b> Поддержка союзников — условный вес сотрудничества, не количество стран. Силовое давление может повышать влияние, одновременно уменьшать поддержку. Готовность отражает обычную армию и её снабжение.</li><li><b>Устойчивость.</b> Показывает внутреннюю способность проводить курс. Неподготовленные реформы и длительные обязательства её уменьшают. Для договора республик нужны экономика ≥55, устойчивость ≥45 и два этапа подготовки.</li><li><b>Исторический финал.</b> Нужно последовательно выбирать историческое направление во всех главах. Включите подсказки над решениями. Возвращение к отдельному реальному решению не отменяет уже сделанного альтернативного выбора.</li><li><b>Сохранение СССР.</b> Подготовьте экономику, заключите союзный договор в 1990 году и исполните его в 1991-м. Для сохранения нужны экономика ≥55 и устойчивость ≥50. Для победы СССР дополнительно: экономика ≥75, союзники ≥65, влияние ≥45, сумма экономики и союзников выше суммы соперника минимум на 20.</li><li><b>Военная развилка.</b> Напряжённость 100 или прямое столкновение на Кубе открывают чрезвычайный выбор. Переговоры требуют доверия ≥25 или канала связи. Обычная война учитывает 40% готовности, 30% экономики и 30% союзной поддержки. Ядерное применение ведёт к отдельной катастрофической концовке.</li></ol><p>Шкалы ограничены 0–100. Между главами напряжённость меняется на поправку нового события −5; канал связи добавляет снижение на 2. При доверии ниже 20 положительная эскалация получает +3; после трёх силовых решений следующие такие решения получают ещё +2. Числа не являются вероятностями или исторической статистикой.</p><p><b>Управление:</b> кнопки или клавиши 1–3; Tab и Enter; Esc закрывает окно. Автосохранение хранится в этом браузере. Сохранения версии 1 оставлены отдельно: новый сценарий начинается новой кампанией.</p><p>Для игры без интернета откройте index.html. Для чтения источников нужен интернет. «Журнал решений» сохраняет выбранные ветки, последствия и исторические справки в TXT.</p>`);
  }''')
function('exportJournal', r'''  function exportJournal() {
    const lines=['НА ГРАНИ — ЖУРНАЛ КАМПАНИИ, ВЕРСИЯ 2',`Сторона: ${D.sides[state.side]}`,'Численные эффекты и альтернативные исходы — условная модель.',''];
    for(const h of state.history){
      const ep=h.scene,c=h.selected,real=D.episodes.find(e=>e.id===h.episode);
      lines.push(`${ep.year}. ${ep.title}`,`Руководитель: ${ep.leaders[state.side]}`,`Обстоятельства: ${ep.context}`,`Ветка: ${ep.branch?.reason||'историческая исходная ситуация'}`,`Решение: ${c.title}`,`Почему важно: ${c.why||c.detail}`,`Курс: ${c.historical?'историческое направление':'альтернативный'}`,`В вашей ветке: ${c.outcome}`,Object.entries(D.metrics).map(([k,l])=>`${l}: ${h.before[k]} → ${h.after[k]} (${sign(h.delta[k])})`).join('; '),Object.entries(D.strategic).map(([k,l])=>`${l}: ${h.beforeStrategic[k]} → ${h.afterStrategic[k]} (${sign(h.strategicDelta[k])})`).join('; '),...h.notes);
      if(h.war)lines.push(`Военная развилка: ${h.war.title}`,h.war.text,Object.entries(D.metrics).map(([k,l])=>`${l} ${sign(h.war.delta[k])}`).join('; '));
      lines.push(`В действительности: ${real.history}`,...[...new Set([...real.sources,...(ep.branch?.sources||[])])].map(id=>`${D.sources[id].title}: ${D.sources[id].url}`),'');
    }
    if(state.ending)lines.push(`Итог: ${E.endings[state.ending].title}`,E.endings[state.ending].text);
    const blob=new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');
    link.href=url;link.download=`На грани — журнал ${D.sides[state.side]}.txt`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }'''.replace("'\\uFEFF'", "'\uFEFF'").replace("'\\r\\n'", "'\r\n'"))
# Actual JS escape sequences, not newline characters inside quoted literals.
s=s.replace("lines.join('\r\n')", "lines.join('\\r\\n')")
s=s.replace("case 'choose': makeChoice(Number(button.dataset.choice)); break;", "case 'choose': makeChoice(Number(button.dataset.choice)); break;\n      case 'historical-hints': showHistoricalHints=!showHistoricalHints; campaign(); break;\n      case 'war-choice': if(state?.phase==='war') { state=E.chooseWar(state,Number(button.dataset.choice)); persist(); campaign(); focusTop(); } break;")
s=s.replace("if (state?.phase === 'result')", "if (['result','war_result'].includes(state?.phase))")
s=s.replace("if (!state || !['escalation','exhaustion'].includes(state.ending)) break;", "if (!state || !(state.ending === 'exhaustion' || state.ending === 'nuclear' || state.ending?.startsWith('war_'))) break;")
s=s.replace("if (/^[123]$/.test(event.key) && view === 'game' && state?.phase === 'decision') { event.preventDefault(); makeChoice(Number(event.key) - 1); }", "if (/^[123]$/.test(event.key) && view === 'game') { if(state?.phase === 'decision') { event.preventDefault(); makeChoice(Number(event.key)-1); } else if(state?.phase === 'war') { event.preventDefault(); const button=app.querySelector('[data-action=\"war-choice\"][data-choice=\"'+(Number(event.key)-1)+'\"]'); if(button && !button.disabled) button.click(); } }")
p.write_text(s,encoding='utf-8')
